name: Merge to Main

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Node sample
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run linting rules and tests
        run: npm ci

      - name: Linting source code
        run: npm run lint

      - name: Test code
        run: npm run test
