name: Publish Package to npmjs

on:
  workflow_dispatch:
    # release:
    #     types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"

      - name: Install latest NPM
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Config git metadata
        run: |
          git config --global user.name 'Alfin Andri'
          git config --global user.email 'alfin.andri@gmail.com'

      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
